<#
.SYNOPSIS
Installs the HFM daemon as a Windows service, using WinSW (https://github.com/winsw/winsw, MIT).

.DESCRIPTION
Creates daemon\service\<ServiceId>.exe (WinSW) and <ServiceId>.xml, which start the daemon on EPM's
own Java 8 with the same command line as run-daemon.ps1. The service starts automatically (delayed,
so EPM's services come up first), restarts if the daemon dies, and writes rotating logs to
daemon\logs. Stopping it lets the daemon close its HFM sessions cleanly.

Run from an elevated PowerShell on the EPM server, after building the jars:
  powershell -ExecutionPolicy Bypass -File scripts\install-service.ps1 -Account -Start

Re-running it after a change (config path, EPM paths, JVM options) rewrites the service's
XML; restart the service to apply it. Afterwards manage it with services.msc or:
  daemon\service\hfm-daemon.exe start|stop|restart|status

.PARAMETER Config
Daemon properties file. Default: config\daemon.properties.
.PARAMETER ServiceId
Windows service name. Default: hfm-daemon.
.PARAMETER WinswExe
Path to a copy of WinSW.NET461.exe v2.12.0 you downloaded yourself, for servers without
internet access. Its SHA-256 is checked either way.
.PARAMETER Account
Prompt for the Windows account the service runs as. Use the account the EPM services run as;
the default (LocalSystem) may not be able to read the EPM instance.
.PARAMETER Start
Start the service after installing.
.PARAMETER GenerateOnly
Write the service files but do not install anything (to review them first).
#>
param(
    [string]$Config = '',
    [string]$ServiceId = 'hfm-daemon',
    [string]$DisplayName = 'HFM MCP Daemon',
    [string]$WinswExe = '',
    [switch]$Account,
    [switch]$Start,
    [switch]$GenerateOnly
)
. "$PSScriptRoot\epm-env.ps1"

$WinswVersion = '2.12.0'
$WinswUrl = "https://github.com/winsw/winsw/releases/download/v$WinswVersion/WinSW.NET461.exe"
# SHA-256 of that release asset (WinSW.NET461.exe, 655872 bytes), recorded when this script was written.
$WinswSha256 = 'B5066B7BBDFBA1293E5D15CDA3CAAEA88FBEAB35BD5B38C41C913D492AADFC4F'

if ($ServiceId -notmatch '^[A-Za-z0-9_-]+$') { throw "ServiceId may only contain letters, digits, - and _" }
if (-not $GenerateOnly) {
    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "Run this from an elevated (Administrator) PowerShell."
    }
}

$cmd = Get-DaemonCommand $Config
$serviceDir = Join-Path $DaemonRoot 'service'
$logDir = Join-Path $DaemonRoot 'logs'
New-Item -ItemType Directory -Force -Path $serviceDir, $logDir | Out-Null
$exe = Join-Path $serviceDir "$ServiceId.exe"
$xmlPath = Join-Path $serviceDir "$ServiceId.xml"

# ---- WinSW executable -----------------------------------------------------------------------
if ($WinswExe) {
    Copy-Item -LiteralPath $WinswExe -Destination $exe -Force
} elseif (-not (Test-Path $exe)) {
    Write-Host "Downloading WinSW $WinswVersion from $WinswUrl"
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $WinswUrl -OutFile $exe -UseBasicParsing
}
$hash = (Get-FileHash -LiteralPath $exe -Algorithm SHA256).Hash
if ($hash -ne $WinswSha256) {
    Remove-Item -LiteralPath $exe -Force
    throw "WinSW checksum mismatch (got $hash, expected $WinswSha256). Download WinSW.NET461.exe v$WinswVersion and pass it with -WinswExe."
}

# ---- Service definition -----------------------------------------------------------------------
# Quotes one argument for the Windows command line (CommandLineToArgvW rules).
function ConvertTo-CommandLineArg([string]$a) {
    if ($a -notmatch '[\s"]' -and $a.Length -gt 0) { return $a }
    $escaped = $a -replace '(\\*)"', '$1$1\"'
    $escaped = $escaped -replace '(\\+)$', '$1$1'
    return '"' + $escaped + '"'
}
function Esc([string]$s) { return [System.Security.SecurityElement]::Escape($s) }

$argLine = ($cmd.Arguments | ForEach-Object { ConvertTo-CommandLineArg $_ }) -join ' '
$xml = @"
<!-- Generated by install-service.ps1; re-run it rather than editing this file. -->
<service>
  <id>$(Esc $ServiceId)</id>
  <name>$(Esc $DisplayName)</name>
  <description>Oracle HFM daemon for the HFM MCP server (config: $(Esc $cmd.Config)).</description>
  <executable>$(Esc $cmd.Java)</executable>
  <arguments>$(Esc $argLine)</arguments>
  <workingdirectory>$(Esc $DaemonRoot)</workingdirectory>
  <env name="EPM_ORACLE_HOME" value="$(Esc $env:EPM_ORACLE_HOME)"/>
  <env name="EPM_ORACLE_INSTANCE" value="$(Esc $env:EPM_ORACLE_INSTANCE)"/>
  <startmode>Automatic</startmode>
  <delayedAutoStart>true</delayedAutoStart>
  <stopparentprocessfirst>true</stopparentprocessfirst>
  <stoptimeout>30 sec</stoptimeout>
  <onfailure action="restart" delay="30 sec"/>
  <onfailure action="restart" delay="2 min"/>
  <resetfailure>1 hour</resetfailure>
  <logpath>$(Esc $logDir)</logpath>
  <log mode="roll-by-size">
    <sizeThreshold>10240</sizeThreshold>
    <keepFiles>8</keepFiles>
  </log>
</service>
"@
$null = [xml]$xml   # fail here, not at service start, if the XML is malformed
[IO.File]::WriteAllText($xmlPath, $xml, (New-Object Text.UTF8Encoding($false)))
Write-Host "Wrote $xmlPath"

if ($GenerateOnly) {
    Write-Host "GenerateOnly: nothing installed."
    return
}

# ---- Install / update ------------------------------------------------------------------------
if (Get-Service -Name $ServiceId -ErrorAction SilentlyContinue) {
    Write-Host "Service '$ServiceId' already exists; its definition was updated."
    if ($Start) {
        & $exe restart
        if ($LASTEXITCODE -ne 0) { throw "Restart failed (exit $LASTEXITCODE); see $logDir" }
    } else {
        Write-Host "Restart it to apply: $exe restart"
    }
    return
}

if ($Account) {
    & $exe install /p     # WinSW prompts for the account and password and grants it 'Log on as a service'
} else {
    Write-Warning "Installing to run as LocalSystem. If it cannot read the EPM instance, reinstall with -Account."
    & $exe install
}
if ($LASTEXITCODE -ne 0) { throw "Install failed (exit $LASTEXITCODE)" }
Write-Host "Installed service '$ServiceId' ($DisplayName)."

if ($Start) {
    & $exe start
    if ($LASTEXITCODE -ne 0) { throw "Start failed (exit $LASTEXITCODE); see $logDir" }
    Write-Host "Started. Logs: $logDir"
} else {
    Write-Host "Start it with: $exe start   (or from services.msc)"
}
