package oracle.epm.fm.common.exception;
public class ErrorCodeConsts {
 public static final String CANNOT_AUTHENTICATE_USER_ERROR="EPMHFM-65542", CSS_TOKEN_NOT_AVAILABLE_ERROR="EPMHFM-65555",
 ERROR_CREATING_SESSION_FOR_APPLICATION="EPMHFM-66031", ERROR_INVALID_MEMBER_SELECTED_FOR_DIM="EPMHFM-65756",
 INVALID_MEMBER_ERROR="EPMHFM-65643", INVALID_SESSION_INFO="EPMHFM-66036", INVALID_SSO_TOKEN_ERROR="EPMHFM-65543",
 MEMBER_NOT_FOUND="EPMHFM-65977", USER_NOT_AUTHENTICATED_ERROR="EPMHFM-65541"; }
