#!/usr/bin/env python3
"""Builds the API manifest ApiCheck verifies on the EPM server: every HFM / Thrift class,
constructor, method and field the compiled Oracle backend references, read from its bytecode
(`javap -c -p` output on stdin). Only what the backend links against is listed; constants that
javac inlines (ErrorCodeConsts, HResultConsts) are not references and so are not checked.

Manifest lines:
  C <class> class|interface|any
  K <class> <param types>
  M <class> static|instance <name> <return type> <param types>
  F <class> static|instance <name> <type>
Types use Class.getName() spelling; "-" means no parameters.
"""
import re
import sys

PREFIXES = ("oracle/", "org/apache/thrift/")
PRIMS = {"Z": "boolean", "B": "byte", "C": "char", "S": "short", "I": "int", "J": "long",
         "F": "float", "D": "double", "V": "void"}
REF = re.compile(r"^\s*\d+: (\w+)\s+#\d+(?:,\s*\d+)?\s+// (Method|InterfaceMethod|Field|class) (\S+)")
CATCH = re.compile(r"^\s+\d+\s+\d+\s+\d+\s+Class (\S+)")


def read_type(desc, i):
    """One JVM type descriptor at desc[i:] -> (Class.getName() spelling, next index)."""
    dims = 0
    while desc[i] == "[":
        dims += 1
        i += 1
    if desc[i] == "L":
        end = desc.index(";", i)
        name = desc[i + 1:end].replace("/", ".")
        i = end + 1
        return ("[" * dims + "L" + name + ";") if dims else name, i
    code = desc[i]
    return ("[" * dims + code) if dims else PRIMS[code], i + 1


def parse_method(desc):
    params, i = [], 1
    while desc[i] != ")":
        t, i = read_type(desc, i)
        params.append(t)
    ret, _ = read_type(desc, i + 1)
    return params, ret


def main():
    kinds = {}
    entries = set()

    def note_class(cls, kind):
        if kind == "interface" or kinds.get(cls) in (None, "any"):
            kinds[cls] = kind

    for line in sys.stdin:
        m = CATCH.match(line)
        if m:
            if m.group(1).startswith(PREFIXES):
                note_class(m.group(1).replace("/", "."), "any")
            continue
        m = REF.match(line)
        if not m:
            continue
        opcode, ref_kind, target = m.groups()
        if ref_kind == "class":
            name = target.strip('"')
            if name.startswith(PREFIXES):
                note_class(name.replace("/", "."), "any")
            continue
        owner_member, desc = target.split(":", 1)
        if "." not in owner_member:
            continue  # a member of the class being disassembled: javap omits the owner
        owner, member = owner_member.rsplit(".", 1)
        if not owner.startswith(PREFIXES):
            continue
        cls = owner.replace("/", ".")
        note_class(cls, "interface" if ref_kind == "InterfaceMethod" else "class")
        static = "static" if opcode in ("invokestatic", "getstatic", "putstatic") else "instance"
        member = member.strip('"')
        if ref_kind == "Field":
            ftype, _ = read_type(desc, 0)
            entries.add(f"F {cls} {static} {member} {ftype}")
            continue
        params, ret = parse_method(desc)
        plist = ",".join(params) if params else "-"
        if member == "<init>":
            entries.add(f"K {cls} {plist}")
        else:
            entries.add(f"M {cls} {static} {member} {ret} {plist}")

    print("# HFM / Thrift API referenced by the compiled Oracle backend. Generated by api_manifest.py.")
    for cls in sorted(kinds):
        print(f"C {cls} {kinds[cls]}")
    for e in sorted(entries):
        print(e)


if __name__ == "__main__":
    main()
